language: android
before_install:
 - chmod +x gradlew
 android:
  components:
    - build-tools-26.0.2
    - android-27
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
