language: android
before_install:
 - chmod +x gradlew
android:
  components:
    - build-tools-28.0.3
    - android-27
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
